branch-defaults:
  form:
    environment: app-tracker-dev
    group_suffix: null
global:
  application_name: app-tracker
  branch: null
  default_ec2_keyname: app-tracker-keypair
  default_platform: Python 3.12 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
